camunda.bpm.metrics:
    enabled: false
    db-reporter-activate: false
camunda:
  bpm:
    admin-user:
      id: demo
      password: demo

spring:
  datasource:
    url: jdbc:mysql://192.168.50.12:31106/workflow?characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name:
